create table if not exists public.users (
  id bigint generated by default as identity primary key,
  first_name varchar(100) not null,
  last_name varchar(100) not null,
  email varchar(255) unique not null,
  phone varchar(30) not null,
  city varchar(100) not null,
  country varchar(100) not null,
  password_hash varchar(255) not null,
  profile_image varchar(1024),
  preferred_destinations jsonb not null default '[]'::jsonb,
  travel_preferences jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title varchar(255) not null,
  destination varchar(255) not null,
  description text,
  start_date date not null,
  end_date date not null,
  cover_image varchar(1024),
  budget_limit numeric(12,2) not null,
  travel_type varchar(100) not null,
  status varchar(50) not null,
  destination_count integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.stops (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  city varchar(255) not null,
  order_index integer not null,
  start_date date not null,
  end_date date,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  stop_id bigint not null references public.stops(id) on delete cascade,
  title varchar(255) not null,
  description text,
  activity_date date not null,
  start_time time,
  end_time time,
  cost numeric(10,2),
  order_index integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.checklist_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title varchar(255) not null,
  category varchar(100) not null,
  packed boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists trips_user_id_idx on public.trips(user_id);
create index if not exists stops_trip_id_idx on public.stops(trip_id);
create index if not exists activities_stop_id_idx on public.activities(stop_id);
create index if not exists checklist_items_user_id_idx on public.checklist_items(user_id);
